Use HTTPResponse.read instead of non-existant readall method
fixed "AttributeError: 'HTTPResponse' object has no attribute 'readall'" exceptions after upgrading Python from 3.4.3 to 3.5.0 on ArchLinux

https://docs.python.org/3/library/http.client.html#http.client.HTTPResponse.read
https://docs.python.org/2/library/httplib.html#httplib.HTTPResponse.read